#!/bin/zsh

# 啟用/更新 com.partsouq.vncs-scheduler LaunchAgent（VNCS 汽柴油車籍同步）。
# 與 catalog scheduler 各自持有不同 job 的鎖，兩者可並存。
#
# launchd 沒有使用者的 Desktop／資料夾 TCC 權限，因此 runtime 以 git archive
# stage 到 ~/Library/Application Support 下的 release 目錄執行，不直接跑
# repo 工作樹；Playwright 瀏覽器續用 ~/Library/Caches/ms-playwright。

set -euo pipefail
umask 077

usage() {
  print -u2 "usage: $0 [--no-start]"
}

NO_START=0
if (( $# > 1 )); then
  usage
  exit 2
fi
if (( $# == 1 )); then
  if [[ "$1" != "--no-start" ]]; then
    usage
    exit 2
  fi
  NO_START=1
fi

if [[ "$(/usr/bin/uname -s)" != "Darwin" ]]; then
  print -u2 "the VNCS LaunchAgent installer only supports macOS"
  exit 2
fi

SCRIPT_DIR=${0:A:h}
PROJECT_ROOT=${SCRIPT_DIR:h}
LABEL=com.partsouq.vncs-scheduler
TEMPLATE="$SCRIPT_DIR/$LABEL.plist.template"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
AGENT_PATH="$LAUNCH_AGENTS_DIR/$LABEL.plist"
HOST_STATE_DIR="$HOME/Library/Application Support/partsouq-vncs-scheduler"
LOG_DIR="$HOST_STATE_DIR/logs"
STDOUT_PATH="$LOG_DIR/vncs-scheduler.stdout.log"
STDERR_PATH="$LOG_DIR/vncs-scheduler.stderr.log"
REPO_RUNTIME_PYTHON=${PARTSOUQ_RUNTIME_PYTHON:-$PROJECT_ROOT/.venv/bin/python}
LAUNCHCTL_BIN=${PARTSOUQ_LAUNCHCTL_BIN:-/bin/launchctl}
GIT_BIN=${PARTSOUQ_GIT_BIN:-/usr/bin/git}
UV_BIN=${PARTSOUQ_UV_BIN:-${commands[uv]:-}}
SERVICE_TARGET="gui/$(/usr/bin/id -u)/$LABEL"
DOMAIN_TARGET="gui/$(/usr/bin/id -u)"
READY_TIMEOUT=${PARTSOUQ_LAUNCH_READY_TIMEOUT_SECONDS:-30}

if [[ ! -f "$TEMPLATE" ]]; then
  print -u2 "missing LaunchAgent template: $TEMPLATE"
  exit 2
fi
if [[ ! -x "$PROJECT_ROOT/deploy/run-macos-vncs-scheduler.zsh" ]]; then
  print -u2 "missing executable VNCS scheduler launcher"
  exit 2
fi
if [[ ! -f "$PROJECT_ROOT/.env" ]]; then
  print -u2 "missing $PROJECT_ROOT/.env"
  exit 2
fi
if [[ ! -x "$GIT_BIN" ]]; then
  print -u2 "missing git executable: $GIT_BIN"
  exit 2
fi
if [[ -z "$UV_BIN" || ! -x "$UV_BIN" ]]; then
  print -u2 "missing uv executable"
  exit 2
fi
if [[ ! -x "$REPO_RUNTIME_PYTHON" ]]; then
  print -u2 "missing runtime Python: $REPO_RUNTIME_PYTHON"
  exit 2
fi

TRACKED_CHANGES=$("$GIT_BIN" -C "$PROJECT_ROOT" status --porcelain --untracked-files=no)
if [[ -n "$TRACKED_CHANGES" ]]; then
  print -u2 "refusing to install from an uncommitted tracked worktree"
  exit 2
fi
COMMIT_SHA=$("$GIT_BIN" -C "$PROJECT_ROOT" rev-parse --verify HEAD)
if [[ ! "$COMMIT_SHA" =~ '^[0-9a-f]{40}$' ]]; then
  print -u2 "could not resolve the committed runtime revision"
  exit 2
fi

# 環境檔只保留 VNCS 需要的變數，並在乾淨環境內檢查正式庫名。
typeset -a CONFIG_ENV
CONFIG_ENV=(
  PARTSOUQ_DB_HOST
  PARTSOUQ_DB_PORT
  PARTSOUQ_DB_NAME
  PARTSOUQ_DB_USER
  PARTSOUQ_DB_PASSWORD
  VNCS_BROWSER_HEADLESS
  SCHEDULER_VNCS_INTERVAL_SECONDS
)
typeset -a CONFIG_INPUT_ENV
CONFIG_INPUT_ENV=(
  "HOME=$HOME"
  "PATH=$PATH"
  "TMPDIR=${TMPDIR:-/tmp}"
  "LANG=${LANG:-en_US.UTF-8}"
)
for NAME in "${CONFIG_ENV[@]}"; do
  if (( ${+parameters[$NAME]} )); then
    CONFIG_INPUT_ENV+=("$NAME=${(P)NAME}")
  fi
done
CONFIG_EXPORTS=$(/usr/bin/env -i "${CONFIG_INPUT_ENV[@]}" /bin/zsh -c '
  set -euo pipefail
  ENV_FILE=$1
  shift
  source "$ENV_FILE" >/dev/null
  if [[ "${PARTSOUQ_DB_NAME:-}" != "partsouq_catalog" ]]; then
    print -u2 "VNCS scheduler requires PARTSOUQ_DB_NAME=partsouq_catalog"
    exit 2
  fi
  for NAME in HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy \
      SSL_CERT_DIR SSL_CERT_FILE; do
    if (( ${+parameters[$NAME]} )) && [[ -n "${(P)NAME}" ]]; then
      print -u2 "refusing proxy or custom TLS setting in the VNCS scheduler: $NAME"
      exit 2
    fi
  done
  print -r -- "# Generated by install-macos-vncs-scheduler.zsh; owner-only."
  for NAME in "$@"; do
    if (( ${+parameters[$NAME]} )); then
      VALUE=${(P)NAME}
      print -r -- "export $NAME=${(q)VALUE}"
    fi
  done
' partsouq-env "$PROJECT_ROOT/.env" "${CONFIG_ENV[@]}")

/bin/mkdir -p "$LAUNCH_AGENTS_DIR" "$HOST_STATE_DIR" "$LOG_DIR" "$HOST_STATE_DIR/releases"
/bin/chmod 700 "$HOST_STATE_DIR" "$LOG_DIR" "$HOST_STATE_DIR/releases"

TEMP_CONFIG=$(/usr/bin/mktemp "$HOST_STATE_DIR/.vncs-env.XXXXXX")
print -r -- "$CONFIG_EXPORTS" > "$TEMP_CONFIG"
/bin/chmod 600 "$TEMP_CONFIG"

# ---- release staging -----------------------------------------------------

SAFE_INSTALL_ENV=(
  "HOME=$HOME"
  "PATH=$PATH"
  "TMPDIR=${TMPDIR:-/tmp}"
  "LANG=${LANG:-en_US.UTF-8}"
  "PYTHONDONTWRITEBYTECODE=1"
)

release_is_valid() {
  CANDIDATE=$1
  [[ -d "$CANDIDATE/app/src" \
      && -d "$CANDIDATE/app/.venv" \
      && -f "$CANDIDATE/vncs-scheduler.env" \
      && -f "$CANDIDATE/.install-complete" \
      && -x "$CANDIDATE/app/deploy/run-macos-vncs-scheduler.zsh" \
      && -x "$CANDIDATE/app/.venv/bin/partsouq-scheduler" ]]
}

RUNTIME_RELEASE=""
for CANDIDATE in "$HOST_STATE_DIR/releases/$COMMIT_SHA-"*(N/); do
  if ! release_is_valid "$CANDIDATE"; then
    continue
  fi
  # 環境檔內容不同（例如 DB 密碼輪替）就重建 release。
  if /usr/bin/cmp -s "$TEMP_CONFIG" "$CANDIDATE/vncs-scheduler.env"; then
    RUNTIME_RELEASE=$CANDIDATE
    break
  fi
done

if [[ -z "$RUNTIME_RELEASE" ]]; then
  RELEASE_DIR=$(/usr/bin/mktemp -d "$HOST_STATE_DIR/releases/$COMMIT_SHA-XXXXXX")
  /bin/chmod 700 "$RELEASE_DIR"
  APP_DIR="$RELEASE_DIR/app"
  /bin/mkdir -p "$APP_DIR"
  SOURCE_ARCHIVE=$(/usr/bin/mktemp "$HOST_STATE_DIR/.vncs-src.XXXXXX")
  "$GIT_BIN" -C "$PROJECT_ROOT" archive --format=tar --output="$SOURCE_ARCHIVE" \
    "$COMMIT_SHA" -- pyproject.toml uv.lock README.md src db migrations deploy
  /usr/bin/tar -xf "$SOURCE_ARCHIVE" -C "$APP_DIR"
  /bin/rm -f "$SOURCE_ARCHIVE"
  if [[ -e "$APP_DIR/.git" || -e "$APP_DIR/.env" ]]; then
    print -u2 "committed runtime unexpectedly contains repository identity or local secrets"
    /bin/rm -rf "$RELEASE_DIR"
    exit 2
  fi
  /bin/cp "$TEMP_CONFIG" "$RELEASE_DIR/vncs-scheduler.env"
  /bin/chmod 600 "$RELEASE_DIR/vncs-scheduler.env"

  BASE_PYTHON=$(/usr/bin/env -i "${SAFE_INSTALL_ENV[@]}" \
    "$REPO_RUNTIME_PYTHON" -c 'import sys; print(sys._base_executable)')
  if [[ -z "$BASE_PYTHON" || ! -x "$BASE_PYTHON" ]]; then
    print -u2 "could not resolve the runtime base Python"
    /bin/rm -rf "$RELEASE_DIR"
    exit 2
  fi
  case "${BASE_PYTHON:A}" in
    "$PROJECT_ROOT"/*)
      print -u2 "runtime base Python must not live inside the repository"
      /bin/rm -rf "$RELEASE_DIR"
      exit 2
      ;;
  esac

  if ! /usr/bin/env -i "${SAFE_INSTALL_ENV[@]}" "$UV_BIN" sync \
      --locked \
      --no-dev \
      --no-editable \
      --python "$BASE_PYTHON" \
      --project "$APP_DIR"; then
    print -u2 "failed to build the VNCS runtime virtualenv"
    /bin/rm -rf "$RELEASE_DIR"
    exit 2
  fi
  if ! /usr/bin/env -i "${SAFE_INSTALL_ENV[@]}" \
      "$APP_DIR/.venv/bin/python" -c 'import playwright'; then
    print -u2 "runtime virtualenv is missing the playwright package"
    /bin/rm -rf "$RELEASE_DIR"
    exit 2
  fi
  print -r -- "$COMMIT_SHA" > "$RELEASE_DIR/.install-complete"
  /bin/chmod 600 "$RELEASE_DIR/.install-complete"
  /bin/chmod -R go-rwx "$RELEASE_DIR"
  RUNTIME_RELEASE=$RELEASE_DIR
  print "staged VNCS runtime release: $RUNTIME_RELEASE"
fi

APP_RUNTIME="$RUNTIME_RELEASE/app"
ENV_FILE="$RUNTIME_RELEASE/vncs-scheduler.env"

# ---- LaunchAgent ---------------------------------------------------------

WORK_DIR=$(/usr/bin/mktemp -d "$HOST_STATE_DIR/.install.XXXXXX")
trap 'if [[ -d "$WORK_DIR" ]]; then /bin/rm -rf "$WORK_DIR"; fi' EXIT
TEMP_AGENT="$WORK_DIR/$LABEL.plist"
/bin/cp "$TEMPLATE" "$TEMP_AGENT"
/usr/bin/sed \
  -e "s|__PROJECT_ROOT__|$APP_RUNTIME|g" \
  -e "s|__STDOUT_PATH__|$STDOUT_PATH|g" \
  -e "s|__STDERR_PATH__|$STDERR_PATH|g" \
  -i '' "$TEMP_AGENT"
if /usr/bin/grep -Eq '__[A-Z0-9_]+' "$TEMP_AGENT"; then
  print -u2 "rendered LaunchAgent still contains an unresolved placeholder"
  exit 2
fi
/usr/bin/plutil -lint "$TEMP_AGENT" >/dev/null
/bin/chmod 600 "$TEMP_AGENT"

if (( NO_START )); then
  /bin/mv -f "$TEMP_AGENT" "$AGENT_PATH"
  /bin/chmod 600 "$AGENT_PATH"
  print "LaunchAgent installed without starting: $AGENT_PATH"
  print "Runtime: $APP_RUNTIME"
  exit 0
fi

WAS_LOADED=0
if "$LAUNCHCTL_BIN" print "$SERVICE_TARGET" >/dev/null 2>&1; then
  WAS_LOADED=1
  "$LAUNCHCTL_BIN" bootout "$SERVICE_TARGET"
fi

/bin/mv -f "$TEMP_AGENT" "$AGENT_PATH"
/bin/chmod 600 "$AGENT_PATH"

if ! "$LAUNCHCTL_BIN" bootstrap "$DOMAIN_TARGET" "$AGENT_PATH"; then
  print -u2 "failed to bootstrap $SERVICE_TARGET"
  exit 1
fi

CHILD_RUNNING=0
for (( SECOND = 0; SECOND < READY_TIMEOUT; SECOND++ )); do
  if SERVICE_STATE=$("$LAUNCHCTL_BIN" print "$SERVICE_TARGET" 2>/dev/null \
      | /usr/bin/sed -n 's/^[[:space:]]*state = //p' | /usr/bin/head -n 1) \
      && [[ "$SERVICE_STATE" == "running" ]]; then
    CHILD_RUNNING=1
    break
  fi
  /bin/sleep 1
done
if (( ! CHILD_RUNNING )); then
  print -u2 "VNCS scheduler did not reach the running state; check $STDERR_PATH"
  exit 1
fi
print "LaunchAgent installed and started: $SERVICE_TARGET (commit $COMMIT_SHA)"
print "Runtime: $APP_RUNTIME"
print "Logs: $LOG_DIR"
