#!/bin/zsh

# 啟用/更新 com.partsouq.vncs-scheduler LaunchAgent（VNCS 汽柴油車籍同步）。
# 與 catalog scheduler 各自持有不同 job 的鎖，兩者可並存。

set -euo pipefail
umask 077

usage() {
  print -u2 "usage: $0 [--no-start]"
}

NO_START=0
if (( $# > 1 )); then
  usage
  exit 2
fi
if (( $# == 1 )); then
  if [[ "$1" != "--no-start" ]]; then
    usage
    exit 2
  fi
  NO_START=1
fi

if [[ "$(/usr/bin/uname -s)" != "Darwin" ]]; then
  print -u2 "the VNCS LaunchAgent installer only supports macOS"
  exit 2
fi

SCRIPT_DIR=${0:A:h}
PROJECT_ROOT=${SCRIPT_DIR:h}
LABEL=com.partsouq.vncs-scheduler
TEMPLATE="$SCRIPT_DIR/$LABEL.plist.template"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
AGENT_PATH="$LAUNCH_AGENTS_DIR/$LABEL.plist"
HOST_STATE_DIR="$HOME/Library/Application Support/partsouq-vncs-scheduler"
LOG_DIR="$HOST_STATE_DIR/logs"
STDOUT_PATH="$LOG_DIR/vncs-scheduler.stdout.log"
STDERR_PATH="$LOG_DIR/vncs-scheduler.stderr.log"
LAUNCHCTL_BIN=${PARTSOUQ_LAUNCHCTL_BIN:-/bin/launchctl}
GIT_BIN=${PARTSOUQ_GIT_BIN:-/usr/bin/git}
UV_BIN=${PARTSOUQ_UV_BIN:-${commands[uv]:-}}
RUNTIME_PYTHON=${PARTSOUQ_RUNTIME_PYTHON:-$PROJECT_ROOT/.venv/bin/python}
SERVICE_TARGET="gui/$(/usr/bin/id -u)/$LABEL"
DOMAIN_TARGET="gui/$(/usr/bin/id -u)"
READY_TIMEOUT=${PARTSOUQ_LAUNCH_READY_TIMEOUT_SECONDS:-30}

if [[ ! -f "$TEMPLATE" ]]; then
  print -u2 "missing LaunchAgent template: $TEMPLATE"
  exit 2
fi
if [[ ! -x "$PROJECT_ROOT/deploy/run-macos-vncs-scheduler.zsh" ]]; then
  print -u2 "missing executable VNCS scheduler launcher"
  exit 2
fi
if [[ ! -f "$PROJECT_ROOT/.env" ]]; then
  print -u2 "missing $PROJECT_ROOT/.env"
  exit 2
fi
if [[ ! -x "$GIT_BIN" ]]; then
  print -u2 "missing git executable: $GIT_BIN"
  exit 2
fi
if [[ -z "$UV_BIN" || ! -x "$UV_BIN" ]]; then
  print -u2 "missing uv executable"
  exit 2
fi
if [[ ! -x "$RUNTIME_PYTHON" ]]; then
  print -u2 "missing runtime Python: $RUNTIME_PYTHON"
  exit 2
fi
if [[ ! -x "$PROJECT_ROOT/.venv/bin/partsouq-scheduler" ]]; then
  print -u2 "missing runtime scheduler entrypoint: $PROJECT_ROOT/.venv/bin/partsouq-scheduler"
  exit 2
fi

TRACKED_CHANGES=$("$GIT_BIN" -C "$PROJECT_ROOT" status --porcelain --untracked-files=no)
if [[ -n "$TRACKED_CHANGES" ]]; then
  print -u2 "refusing to install from an uncommitted tracked worktree"
  exit 2
fi
COMMIT_SHA=$("$GIT_BIN" -C "$PROJECT_ROOT" rev-parse --verify HEAD)
if [[ ! "$COMMIT_SHA" =~ '^[0-9a-f]{40}$' ]]; then
  print -u2 "could not resolve the committed runtime revision"
  exit 2
fi

# 環境檔只保留 VNCS 需要的變數，並在乾淨環境內檢查正式庫名。
typeset -a CONFIG_ENV
CONFIG_ENV=(
  PARTSOUQ_DB_HOST
  PARTSOUQ_DB_PORT
  PARTSOUQ_DB_NAME
  PARTSOUQ_DB_USER
  PARTSOUQ_DB_PASSWORD
  VNCS_BROWSER_HEADLESS
  SCHEDULER_VNCS_INTERVAL_SECONDS
)
typeset -a CONFIG_INPUT_ENV
CONFIG_INPUT_ENV=(
  "HOME=$HOME"
  "PATH=$PATH"
  "TMPDIR=${TMPDIR:-/tmp}"
  "LANG=${LANG:-en_US.UTF-8}"
)
for NAME in "${CONFIG_ENV[@]}"; do
  if (( ${+parameters[$NAME]} )); then
    CONFIG_INPUT_ENV+=("$NAME=${(P)NAME}")
  fi
done
CONFIG_EXPORTS=$(/usr/bin/env -i "${CONFIG_INPUT_ENV[@]}" /bin/zsh -c '
  set -euo pipefail
  ENV_FILE=$1
  shift
  source "$ENV_FILE" >/dev/null
  if [[ "${PARTSOUQ_DB_NAME:-}" != "partsouq_catalog" ]]; then
    print -u2 "VNCS scheduler requires PARTSOUQ_DB_NAME=partsouq_catalog"
    exit 2
  fi
  for NAME in HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy \
      SSL_CERT_DIR SSL_CERT_FILE; do
    if (( ${+parameters[$NAME]} )) && [[ -n "${(P)NAME}" ]]; then
      print -u2 "refusing proxy or custom TLS setting in the VNCS scheduler: $NAME"
      exit 2
    fi
  done
  print -r -- "# Generated by install-macos-vncs-scheduler.zsh; owner-only."
  for NAME in "$@"; do
    if (( ${+parameters[$NAME]} )); then
      VALUE=${(P)NAME}
      print -r -- "export $NAME=${(q)VALUE}"
    fi
  done
' partsouq-env "$PROJECT_ROOT/.env" "${CONFIG_ENV[@]}")

/bin/mkdir -p "$LAUNCH_AGENTS_DIR" "$HOST_STATE_DIR" "$LOG_DIR"
/bin/chmod 700 "$HOST_STATE_DIR" "$LOG_DIR"
WORK_DIR=$(/usr/bin/mktemp -d "$HOST_STATE_DIR/.install.XXXXXX")
trap 'if [[ -d "$WORK_DIR" ]]; then /bin/rm -rf "$WORK_DIR"; fi' EXIT
TEMP_CONFIG="$WORK_DIR/vncs-scheduler.env"
print -r -- "$CONFIG_EXPORTS" > "$TEMP_CONFIG"
/bin/chmod 600 "$TEMP_CONFIG"

TEMP_AGENT="$WORK_DIR/$LABEL.plist"
/bin/cp "$TEMPLATE" "$TEMP_AGENT"
/usr/bin/sed \
  -e "s|__PROJECT_ROOT__|$PROJECT_ROOT|g" \
  -e "s|__STDOUT_PATH__|$STDOUT_PATH|g" \
  -e "s|__STDERR_PATH__|$STDERR_PATH|g" \
  -i '' "$TEMP_AGENT"
if /usr/bin/grep -Eq '__[A-Z0-9_]+' "$TEMP_AGENT"; then
  print -u2 "rendered LaunchAgent still contains an unresolved placeholder"
  exit 2
fi
/usr/bin/plutil -lint "$TEMP_AGENT" >/dev/null
/bin/chmod 600 "$TEMP_AGENT"

if (( NO_START )); then
  /bin/mv -f "$TEMP_AGENT" "$AGENT_PATH"
  /bin/chmod 600 "$AGENT_PATH"
  print "LaunchAgent installed without starting: $AGENT_PATH"
  print "Runtime: $PROJECT_ROOT"
  exit 0
fi

WAS_LOADED=0
if "$LAUNCHCTL_BIN" print "$SERVICE_TARGET" >/dev/null 2>&1; then
  WAS_LOADED=1
  "$LAUNCHCTL_BIN" bootout "$SERVICE_TARGET"
fi

/bin/mv -f "$TEMP_AGENT" "$AGENT_PATH"
/bin/chmod 600 "$AGENT_PATH"

if ! "$LAUNCHCTL_BIN" bootstrap "$DOMAIN_TARGET" "$AGENT_PATH"; then
  print -u2 "failed to bootstrap $SERVICE_TARGET"
  exit 1
fi

CHILD_RUNNING=0
for (( SECOND = 0; SECOND < READY_TIMEOUT; SECOND++ )); do
  if SERVICE_STATE=$("$LAUNCHCTL_BIN" print "$SERVICE_TARGET" 2>/dev/null \
      | /usr/bin/sed -n 's/^[[:space:]]*state = //p' | /usr/bin/head -n 1) \
      && [[ "$SERVICE_STATE" == "running" ]]; then
    CHILD_RUNNING=1
    break
  fi
  /bin/sleep 1
done
if (( ! CHILD_RUNNING )); then
  print -u2 "VNCS scheduler did not reach the running state; check $STDERR_PATH"
  exit 1
fi
print "LaunchAgent installed and started: $SERVICE_TARGET (commit $COMMIT_SHA)"
print "Logs: $LOG_DIR"
